version: 2.1

orbs:
  node: circleci/node@5

jobs:
  test-node:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Run install
          command: npm install

  build-node:
    executor: node/default
    steps:
      - checkout
      - run:
          command: npm run build

workflows:
  build-and-test:
    jobs:
      - build-node:
          filters:
            branches:
              only:
                - main2
