version: 2.1
orbs:
  node: circleci/node@5
jobs:
  test-node:
    # Install node dependencies and run tests
    executor: node/default
    steps:
      - checkout
      - run:
          name: Run npm install
          command: npm install
  build-node:
    # Build node project
    executor: node/default
    steps:
      - checkout
      - run:
          name: Run npm install
          command: npm install
      - run:
          name: Build project
          command: npm run build
workflows:
  build-and-test:
    jobs:
      - test-node
      - build-node:
          requires:
            - test-node
