version: 2.1

orbs:
  node: circleci/node@5

jobs:
  test-node:
    executor: node/default
    steps:
      - checkout
      - run: git checkout master
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run install
          command: npm install

  build-node:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run build

workflows:
  build-and-test:
    jobs:
      - test-node
      - build-node:
          requires:
            - test-node