
version: 2.1
orbs:
  node: circleci/node@5
jobs:
  test-node:
    # Install node dependencies and run tests
    executor: node/default
    steps:
      - checkout main
      - node/install-packages:
          pkg-manager: npm
  build-node:
    # Build node project
    executor: node/default
    steps:
      - checkout main
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run build